-- ---------------------------------------------------------------------
-- Script de insercion de catalogos utilizadas para el proyecto N4
-- Base de datos: root
-- Version: Oracle 11g
-- ---------------------------------------------------------------------

-- CATALOGO DE ESTATUS

INSERT INTO ROOT.N4_ESTATUS_SOL (ID, NOMBRE, DESCRIPCION, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (1, 'INICIADA', 'Iniciada', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_ESTATUS_SOL (ID, NOMBRE, DESCRIPCION, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (2, 'EN_RECUPERACION_DOC', 'En recuperación de documentos', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_ESTATUS_SOL (ID, NOMBRE, DESCRIPCION, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (3, 'CANCELADA', 'Cancelada', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_ESTATUS_SOL (ID, NOMBRE, DESCRIPCION, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (4, 'FINALIZADA', 'Finalizada', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

-- CATALOGO DE MOTIVOS DE ESTATUS

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (1, 3, 'CONT_CLI_NO_OK','Contacto al cliente no exitoso', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (2, 3, 'NO_RECEP_DOCS','No se recibieron documentos', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (3, 3, 'CLI_CANC_SOL','Cliente cancela solicitud', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (4, 3, 'COT_NO_OK','Cotejo no exitoso', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (5, 3, 'HIT_EN_LISTAS','Hit en listas', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (6, 3, 'CITA_NO_CONCRET','Cita no concretada', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (7, 4, 'PROC_CREA_CUENTA','En proceso de creación de cuenta', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_MOTIVO_ESTATUS_SOL (ID, ID_STATUS, NOMBRE, MOTIVO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (8, 4, 'EXITOSA', 'Exitosa', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);


-- REGISTRO DE EAC_VIP

INSERT INTO ROOT.N4_EAC_VIP (ID, EMAIL, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_EAC_VIP_ID.NEXTVAL, 'dmayorga@gentera.com', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

-- REGISTRO DE RANGO DE HORAS PARA EAC_VIP

INSERT INTO ROOT.N4_EAC_VIP_HORAS (ID, ID_EAC_VIP, RANGO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_EAC_VIP_HORAS_ID.NEXTVAL, 1, '10:00 am - 12:00 pm', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_EAC_VIP_HORAS (ID, ID_EAC_VIP, RANGO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_EAC_VIP_HORAS_ID.NEXTVAL, 1, '12:00 pm - 02:00 pm', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_EAC_VIP_HORAS (ID, ID_EAC_VIP, RANGO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_EAC_VIP_HORAS_ID.NEXTVAL, 1, '03:00 pm - 05:00 pm', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_EAC_VIP_HORAS (ID, ID_EAC_VIP, RANGO, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_EAC_VIP_HORAS_ID.NEXTVAL, 1, '05:00 pm - 07:00 pm', 1, 'N4_APP', CURRENT_TIMESTAMP, 'N4_APP', CURRENT_TIMESTAMP);

COMMIT;
