-- ---------------------------------------------------------------------
-- Script de insercion de datos dummies utilizados para el proyecto N4
-- Base de datos: root
-- Version: Oracle 11g
-- ---------------------------------------------------------------------

-- SOLICITUDES

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919191', 1, NULL, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919192', 2, NULL, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919193', 3, 1, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919194', 3, 2, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919195', 3, 3, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919196', 3, 4, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919197', 3, 5, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919198', 3, 6, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919199', 4, 1, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919200', 4, 2, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919201', 1, NULL, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_SOLICITUD (GUID, ID_STATUS, ID_MOTIVO_STATUS, CURP, FECHANACIMIENTO, CODIGOPOSTAL, IDBP, ACCOUNT, INVESTMENT, OPORTUNITY, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES ('AEMW12919202', 2, NULL, 'AEMW920726HTCLRL04', '26/07/1992', 99999, null, null, null, null, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

-- CITAS

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919191', 1, 1, '12/05/2017', 1, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919191', 1, 1, '11/05/2017', 0, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919191', 1, 1, '10/05/2017', 0, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919192', 1, 2, '10/05/2017', 1, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919193', 1, 3, '10/05/2017', 1, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919194', 1, 4, '10/05/2017', 1, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919195', 1, 2, '10/05/2017', 1, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919196', 1, 3, '10/05/2017', 1, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);

INSERT INTO ROOT.N4_CITAS (ID, ID_SOLICITUD, ID_EAC_VIP, ID_EAC_VIP_HORA, FECHA, STATUS, REFESTADOREG, DESUSERCREAREG, STPCREAREG, DESUSERMODIFICAREG, STPMODIFICAREG) VALUES (ROOT.N4_CITAS_ID.NEXTVAL, 'AEMW12919197', 1, 4, '10/05/2017', 1, 1, 'ADMAYORGA', CURRENT_TIMESTAMP, 'ADMAYORGA', CURRENT_TIMESTAMP);


COMMIT;
